classDiagram
  direction LR

  class hmif_organizer {
    <<object>>
    +int id = 2
    +string name = "HMIF UNRAM"
    +string role = "organizer"
  }

  class esports_category {
    <<object>>
    +int id = 4
    +string name = "eSports and Gaming"
  }

  class efootball_event {
    <<object>>
    +int id = 22
    +string title = "Turnamen eFootball 2026 Campus Edition"
    +int owner_id = 2
    +int category_id = 4
    +int price = 50000
  }

  class akbar_user {
    <<object>>
    +int id = 6
    +string name = "Muhammad Akbar - Arthur"
    +string role = "user"
  }

  class booking_23 {
    <<object>>
    +int id = 23
    +int user_id = 6
    +int event_id = 22
    +string status = "pending"
  }

  class favorite_5 {
    <<object>>
    +int id = 5
    +int user_id = 6
    +int event_id = 22
  }

  class comment_12 {
    <<object>>
    +int id = 12
    +int user_id = 6
    +int event_id = 22
    +string comment = "Apakah peserta harus bawa stik sendiri?"
  }

  hmif_organizer -- efootball_event : menyelenggarakan
  esports_category -- efootball_event : mengkategorikan
  akbar_user -- booking_23 : membuat
  efootball_event -- booking_23 : menerima booking
  akbar_user -- favorite_5 : menambahkan
  efootball_event -- favorite_5 : difavoritkan
  akbar_user -- comment_12 : menulis
  efootball_event -- comment_12 : menerima komentar